// lib/planetsData.ts
import { Planet } from "@/lib/Types"

export const PLANETS_DATA: Planet[] = [
  {
    id: "mercure",
    englishName: "Mercury",
    gravity: 3.7,
    meanRadius: 2439.7,
    sideralOrbit: 87.969,
    sideralRotation: 1407.6,
    moons: null,
    avgTemp: 440,
    mass: { massValue: 3.302, massExponent: 23 },
    density: 5.427,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "venus",
    englishName: "Venus",
    gravity: 8.87,
    meanRadius: 6051.8,
    sideralOrbit: 224.701,
    sideralRotation: -5832.6,
    moons: null,
    avgTemp: 737,
    mass: { massValue: 4.8685, massExponent: 24 },
    density: 5.243,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "terre",
    englishName: "Earth",
    gravity: 9.8,
    meanRadius: 6371,
    sideralOrbit: 365.256,
    sideralRotation: 23.9345,
    moons: [{ moon: "La Lune", rel: "" }],
    avgTemp: 288,
    mass: { massValue: 5.9724, massExponent: 24 },
    density: 5.514,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "mars",
    englishName: "Mars",
    gravity: 3.71,
    meanRadius: 3389.5,
    sideralOrbit: 686.971,
    sideralRotation: 24.6229,
    moons: [
      { moon: "Phobos", rel: "" },
      { moon: "Deimos", rel: "" },
    ],
    avgTemp: 210,
    mass: { massValue: 6.4171, massExponent: 23 },
    density: 3.933,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "jupiter",
    englishName: "Jupiter",
    gravity: 24.79,
    meanRadius: 69911,
    sideralOrbit: 4332.589,
    sideralRotation: 9.9259,
    moons: Array.from({ length: 95 }, (_, i) => ({ moon: `Moon ${i + 1}`, rel: "" })),
    avgTemp: 165,
    mass: { massValue: 1.8982, massExponent: 27 },
    density: 1.326,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "saturne",
    englishName: "Saturn",
    gravity: 10.44,
    meanRadius: 58232,
    sideralOrbit: 10759.22,
    sideralRotation: 10.656,
    moons: Array.from({ length: 146 }, (_, i) => ({ moon: `Moon ${i + 1}`, rel: "" })),
    avgTemp: 134,
    mass: { massValue: 5.6834, massExponent: 26 },
    density: 0.687,
    discoveredBy: "",
    discoveryDate: "",
  },
  {
    id: "uranus",
    englishName: "Uranus",
    gravity: 8.87,
    meanRadius: 25362,
    sideralOrbit: 30688.5,
    sideralRotation: -17.24,
    moons: Array.from({ length: 28 }, (_, i) => ({ moon: `Moon ${i + 1}`, rel: "" })),
    avgTemp: 76,
    mass: { massValue: 8.6810, massExponent: 25 },
    density: 1.271,
    discoveredBy: "William Herschel",
    discoveryDate: "13/03/1781",
  },
  {
    id: "neptune",
    englishName: "Neptune",
    gravity: 11.15,
    meanRadius: 24622,
    sideralOrbit: 60182,
    sideralRotation: 16.11,
    moons: Array.from({ length: 16 }, (_, i) => ({ moon: `Moon ${i + 1}`, rel: "" })),
    avgTemp: 72,
    mass: { massValue: 1.0243, massExponent: 26 },
    density: 1.638,
    discoveredBy: "Johann Galle",
    discoveryDate: "23/09/1846",
  },
]